appid: "my_single_appid"
secret: "my_single_secret"
token:    "my_token"
access_token: "C:/Users/[username]/wechat_access_token"
encrypt_mode: false # if true must fill encoding_aes_key
encoding_aes_key:  "my_encoding_aes_key"
jsapi_ticket: "C:/Users/[user_name]/wechat_jsapi_ticket"
